//
//  ThreadSummary.swift
//  MessageAI
//
//  Created by Dev Agent (James) on 10/23/25.
//  Story 3.1: Cloud Functions Infrastructure for AI Services
//

import Foundation

/// Thread summary generated by AI
///
/// Contains a summary of a conversation thread with key points,
/// participants, and metadata about when it was generated.
struct ThreadSummary: Codable {
    /// The summary text (150-300 words)
    let summary: String

    /// Key points extracted from the conversation
    let keyPoints: [String]

    /// Priority messages that need attention
    let priorityMessages: [PriorityMessage]

    /// Detected meeting needs and scheduled meetings
    let meetings: [Meeting]

    /// Action items extracted from the conversation
    let actionItems: [ActionItem]

    /// Decisions made during the conversation
    let decisions: [Decision]

    /// Participant names in the conversation
    let participants: [String]

    /// Date range of the conversation
    let dateRange: String

    /// When the summary was generated
    let generatedAt: Date

    /// Whether this result came from cache
    let cached: Bool

    /// Number of new messages since this summary was cached (0 if fresh)
    let messagesSinceCache: Int

    /// For Firestore cache: ID of last message analyzed (staleness detection)
    let lastMessageId: String?

    /// For Firestore cache: Number of messages analyzed (staleness detection)
    let messageCount: Int?
}
